### ISSUE TITLE
No compile TrinityCore

### ISSUE THREAD

**Issue by Laintime** [EmuDevs/Mercenary#10]
Plz update fo last trinity,no compile afte https://github.com/TrinityCore/TrinityCore/commit/ff31a1d9eddccca5f8077bb35cd5a7f7740f467d

**Comment by Easelm** [comment]
I'm already fixing it. Forgot to retest TC again, hence the outdated methods.

**Comment by Laintime** [comment]
Thanks!!Mercenary sistem very nice.

**Comment by Easelm** [comment]
f48a9dab1f1d0cffcf06c85ae21eb6b68a7b3465

Fixed errors. Further testing needs to be on Linux since I'm still updating my source.

**Comment by Easelm** [comment]
Tested and works fine. Closing..

**Comment by Laintime** [comment]
No't fix 
Linking CXX static library libgame.a
[ 35%] Built target game
[ 35%] Built target authPCH.cpp_dephelp
[ 35%] Built target generate_authPCH.cpp
[ 36%] Built target authserver
[ 36%] Built target ScriptPCH.cpp_dephelp
[ 36%] Built target generate_ScriptPCH.cpp
[ 99%] Built target scripts
[ 99%] Built target worldPCH.cpp_dephelp
[ 99%] Built target generate_worldPCH.cpp
Linking CXX executable worldserver
../game/libgame.a(DBCStores.cpp.o): In function `LoadDBCStores(std::string const&)':
DBCStores.cpp:(.text+0x5b6e): undefined reference to `sSpellIconStore'
../game/libgame.a(MercenaryMgr.cpp.o): In function `MercenaryMgr::GetSpellIcon(unsigned int, WorldSession*) const':
MercenaryMgr.cpp:(.text+0x23b2): undefined reference to `sSpellIconStore'
MercenaryMgr.cpp:(.text+0x24fb): undefined reference to `sSpellIconStore'
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:205: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1350: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Laintime** [comment]
Yes yes yes.I use patch,transmogrification,ac2,vip,multi-vendor,maybe conflict transmogrification?

**Comment by Easelm** [comment]
Depends on what files those patches edited. But, the error you are getting doesn't look like it is related to diff conflicts as I think the diff wouldn't apply. I know diffs won't apply if there's any errors.

**Comment by Laintime** [comment]
Pleas paste custom cmakelist.txt

**Comment by Laintime** [comment]
http://pastebin.com/1uUV4PGv 
It's my patch fo repo,plz check error(

**Comment by Easelm** [comment]
CMakeLists.txt file has nothing to do with it. What have you done to try and fix this? On a FRESH TrinityCore, Eluna TC and MaNGOS Two it works fine. However, if you have other custom content I can't really help you since that's mainly your issue (not trying to be belligerent).
