### ISSUE TITLE
fix MercenaryMgr.cpp

### ISSUE THREAD

**Issue by catalin82** [EmuDevs/Mercenary#12]
Issue that cause crash to server. In MercenaryMgr.cpp at line 116:

**result = CharacterDatabase.Query("SELECT Id, ownerGUID, role, displayId, race, gender, type, strength, agility, stamina, intellect, spirit, summoned FROM mercenaries");
    if (result)**

must be
    **result = CharacterDatabase.Query("SELECT Id, ownerGUID, role, displayId, race, gender, type, summoned FROM mercenaries");
    if (result)**

since creature no longer update its status from DB.

**Comment by Easelm** [comment]
Geez. I apparently forgot everything that night. Thanks.
