### ISSUE TITLE
On Windows Diff apply error

### ISSUE THREAD

**Issue by JoNMii** [EmuDevs/Mercenary#14]
Hi,
it says patch failed error on cmakelist.txr but that line comes by default

**Comment by Easelm** [comment]
Thanks for reporting that. For now, remove the CMakeLists.txt edit from the diff. Been busy so I haven't had a chance to look on github lately. Guess the CMakeLists.txt edit is kinda pointless to keep in the diff since all you are doing is adding Custom/mercenary_gossip.cpp in it.

**Comment by JoNMii** [comment]
Its the first mod, im using clean Trinty

**Comment by Easelm** [comment]
No worries. I'll be updating everything soon since this system is a bit behind in official commits.
