### ISSUE TITLE
Mercenary NPC not showing any choices

### ISSUE THREAD

**Issue by Fennobadger** [EmuDevs/Mercenary#16]
Issues with Mercenary Master. Only showing greeting in gossip.
Using ElunaWotlk source and latest Mercenary package from github.
Diff go to code without any warnings and code compliles without warnings.
Have applied sql-files to databases.
![image](https://cloud.githubusercontent.com/assets/16900632/12583865/72ccc548-c44d-11e5-8e58-f7cc648f9210.png)

**Comment by Easelm** [comment]
Did you set up the mercenary_gossip.cpp in ScriptLoader.cpp?

Following the recent commit I did 08fbf039af577b3e2c199eb254620104c9eb2b75.

> Removed ScriptLoader.cpp addition in the diff as that can cause conflicts if you have already edited that file. To combat this I updated the Finalized Installation portion of the TrinityCore and Eluna WotLK tutorials with a reminder of setting up mercenary_gossip.cpp in ScriptLoader.cpp.

**Comment by Fennobadger** [comment]
It seems that I forgot that as I added several other things at the same. My bad.
That script setup fixed this issue.
Thank you for replying.

**Comment by Easelm** [comment]
No problem. Glad it was resolved. :P
