### ISSUE TITLE
Compile ubuntu 15.04

### ISSUE THREAD

**Issue by Laintime** [EmuDevs/Mercenary#9]
Compile error
http://pastebin.com/C71Upf36

**Comment by Easelm** [comment]
After implementing the project, did you re-cmake, did make clean, and then make again? It should work if you did.

**Comment by Laintime** [comment]
I'm git clone and build

**Comment by Easelm** [comment]
What? When you apply the diff and add the Mercenary files to the project, you need to run `cmake` again, `make clean` and finally `make`.

**Comment by Re3os** [comment]
I'm apply the diff and add the Mercenary files to the project,git commite to repositories and build to remote server.

**Comment by Laintime** [comment]
I'm apply the diff and add the Mercenary files to the project,git commite to repositories and build to remote server.

**Comment by Laintime** [comment]
Fix
